#!/usr/bin/env python3

import sys
from src import utils
from src import pacman as pac_


def main():
    filePath: str
    arg1: str
    arg2: str

    try:
        if (len(sys.argv) == 4):
            filePath = sys.argv[1]
            utils.checkFile(filePath)
            mapContent = open(filePath)
            arg1 = sys.argv[2]
            arg2 = sys.argv[3]
            utils.checkArgumentFormat(arg1, arg2)
            pac_.pacman(mapContent, arg1, arg2)
        else:
            raise RuntimeError("Wrong input.")
    except (IOError, RuntimeError, ValueError) as e:
        print(e)
        exit(84)
    return 0


main()
